- name: Create EC2_instances and R53
  hosts: local
  connection: local
  vars_files:
    - ec2_instance.yaml
  tasks:
    - name: Creating EC2_instances
      amazon.aws.ec2_instance:
        name: "{{item}}"
        vpc_subnet_id: "{{vpc_subnet}}"
        instance_type: "{{instance_type}}"
        security_group: "{{security_group}}"
        image_id: "{{image_id}}"
      loop: "{{instances_names}}"
      register: ec2details

    - name: EC2_instance details
      ansible.builtin.debug:
        msg: "{{ec2details}}"

    - name: Creating R53 Private IP records
      amazon.aws.route53:
        state: present
        zone: "{{zone}}"  #Actual Domain name
        record: "{{item.item}}.{{zone}}"  #Domine name like "mysql.gangs.shop"
        type: A     #Record type
        ttl: 1
        value: "{{item.instances[0].private_ip_address}}"  #It means IP's of ec2-instance that we creted 
        wait: true
        #overwrite: true   #It will overwrite the exiting IP's
      loop: "{{ec2details.results}}"

    - name: Creating R53 Public IP records
      amazon.aws.route53:
        state: present
        zone: "{{zone}}"  #Actual Domain name
        record: "{{zone}}"  #Domine name like "mysql.gangs.shop"
        type: A     #Record type
        ttl: 1
        value: "{{item.instances[0].public_ip_address}}"  #It means IP's of ec2-instance that we creted 
        wait: true
        #overwrite: true   #It will overwrite the exiting IP's
      loop: "{{ec2details.results}}"
      when: item.item == "frontend"